module Implicit.Language.Shift.Properties where

open import Implicit.Language.Base
open import Implicit.Language.Shift.Base

↑ty-unique :
    A ↑ty k ⇘ A₁
  → A ↑ty k ⇘ A₂
  → A₁ ≡ A₂
↑ty-unique ↑ty-int ↑ty-int = refl
↑ty-unique ↑ty-var ↑ty-var = refl
↑ty-unique (↑ty-arr up1 up3) (↑ty-arr up2 up4) rewrite ↑ty-unique up1 up2 | ↑ty-unique up3 up4 = refl
↑ty-unique (↑ty-∀ up1) (↑ty-∀ up2) rewrite ↑ty-unique up1 up2 = refl

-- proof is generated by auto
↑ty-total : ∀ (A : Type m) (k)
  → ∃ λ A'
  → A ↑ty k ⇘ A'
↑ty-total Int k = ⟨ Int , ↑ty-int ⟩
↑ty-total (‶ X) k = ⟨ ‶ punchIn k X , ↑ty-var ⟩
↑ty-total (A `→ A₁) k = ⟨ ↑ty-total A k .proj₁ `→ ↑ty-total A₁ k .proj₁ ,
                         ↑ty-arr (↑ty-total A k .proj₂) (↑ty-total A₁ k .proj₂) ⟩
↑ty-total (`∀ A) k = ⟨ `∀ ↑ty-total A (#S k) .proj₁ , ↑ty-∀ (↑ty-total A (#S k) .proj₂)⟩

↑ty0-total : ∀ (A : Type m)
  → ∃ λ A'
  → ↑ty0 A ⇘ A'
↑ty0-total A = ↑ty-total A #0

-- shifted
↑ty-shifted : ∀ {A : Type m} {A' k}
  → A ↑ty k ⇘ A'
  → Shifted A' k
↑ty-shifted ↑ty-int = sfd-int
↑ty-shifted {k = k} (↑ty-var {X = X}) = sfd-var (punchInᵢ≢i k X)
↑ty-shifted (↑ty-arr up up₁) = sfd-arr (↑ty-shifted up) (↑ty-shifted up₁)
↑ty-shifted (↑ty-∀ up) = sfd-∀ (↑ty-shifted up)

postulate
  ↑ty-comm : k₁ #≤ k₂
           → A ↑ty k₁ ⇘ B
           → B ↑ty #S k₂ ⇘ C
           → A ↑ty k₂ ⇘ D
           → D ↑ty (inject₁ k₁) ⇘ C         

private variable
  A₀ Aₖ Aₖ₊₁ : Type m

↑ty-comm0 : ↑ty0 A ⇘ A₀
          → A₀ ↑ty #S k ⇘ Aₖ₊₁
          → A ↑ty k ⇘ Aₖ
          → ↑ty0 Aₖ ⇘ Aₖ₊₁
↑ty-comm0 up1 up2 up3 = ↑ty-comm {k₁ = #0} z≤n up1 up2 up3

  
