module Examples where

data Example = Example
  { exampleName :: String
  , exampleString :: String
  }
  deriving (Eq, Show)

examplesList :: [Example]
examplesList =
  [ Example "A1" "lambda x. lambda y. y"
  , Example "A1 (Fc translation 1)" "Lambda a. Lambda b. (lambda x. lambda y. y) : a -> b -> b"
  , Example "A1 (Fc translation 1, uncurried)" "Lambda a. Lambda b. (lambda {x, y}. y) : {a, b} -> b"
  , Example "A1 (Fc translation 2)" "Lambda a. Lambda b. lambda x : a. lambda y : b. y"
  , Example "A1 (Fc translation 2, uncurried)" "Lambda a. Lambda b. lambda {x : a, y : b}. y"
  , Example "A1 (uncurried)" "lambda {x, y}. y"
  , Example "A2" "choose id"
  , Example "A2 (uncurried)" "choose {id}"
  , Example "A3" "choose nil ids"
  , Example "A3 (Fc translation)" "choose (nil : [forall a. a -> a]) ids"
  , Example "A3 (uncurried)" "choose {nil, ids}"
  , Example "A3 (Fc translation, uncurried)" "choose {(nil : [forall a. {a} -> a]), ids}"
  , Example "A4" "lambda x. x x"
  , Example "A4 (Fc translation 1)" "(lambda x. x x) : (forall a. a -> a) -> (forall a. a -> a)"
  , Example "A4 (Fc translation 2)" "lambda x : (forall a. a -> a). x x"
  , Example "A4 (uncurried)" "lambda {x}. x x"
  , Example "A4 (Fc translation 1, uncurried)" "(lambda {x}. x {x}) : {forall a. {a} -> a} -> (forall a. {a} -> a)"
  , Example "A4 (Fc translation 2, uncurried)" "lambda {x : forall a. {a} -> a}. x {x}"
  , Example "A5" "id auto"
  , Example "A5 (uncurried)" "id {auto}"
  , Example "A6" "id auto'"
  , Example "A6 (uncurried)" "id {auto'}"
  , Example "A7" "choose id auto"
  , Example "A7 (Fc translation)" "choose (id @ (forall a. a -> a)) auto"
  , Example "A7 (uncurried)" "choose {id, auto}"
  , Example "A7 (Fc translation, uncurried)" "choose {(id @ (forall a. {a} -> a)), auto}"
  , Example "A8" "choose id auto'"
  , Example "A8 (Fc translation 1)" "choose (Lambda a. lambda f. id f @ a : (forall b. b -> b) -> a -> a) auto'"
  , Example "A8 (Fc translation 2)" "choose (Lambda a. lambda f. lambda x. id f x : (forall b. b -> b) -> a -> a) auto'"
  , Example "A8 (Fc translation 3)" "choose (Lambda a. lambda f : forall b. b -> b. id f @ a) auto'"
  , Example "A8 (uncurried)" "choose {id, auto'}"
  , Example "A8 (Fc translation 1, uncurried)" "choose {((Lambda a. lambda {f}. id {f @ a}) : ({forall b. {b} -> b} -> {a} -> a)), auto'}"
  , Example "A8 (Fc translation 2, uncurried)" "choose {(Lambda a. lambda {f}. lambda {x}. id {f} {x}) : ({forall b. {b} -> b} -> {a} -> a), auto'}"
  , Example "A8 (Fc translation 3, uncurried)" "choose {(Lambda a. lambda {f : forall b. {b} -> b}. id {(f @ a)}), auto'}"
  , Example "A9" "f (choose id) ids"
  , Example "A10" "poly id"
  , Example "A10 (uncurried)" "poly {id}"
  , Example "A11" "poly (lambda x. x)"
  , Example "A11 (Fc translation)" "poly (Lambda a. lambda x. x)"
  , Example "A11 (uncurried)" "poly {lambda {x}. x}"
  , Example "A11 (Fc translation, uncurried)" "poly {Lambda a. lambda {x}. x}"
  , Example "A12" "id poly (lambda x. x)"
  , Example "A12 (Fc translation)" "id poly (Lambda a. lambda x. x)"
  , Example "A12 (uncurried)" "id {poly} {lambda {x}. x}"
  , Example "A12 (Fc translation, uncurried)" "id {poly} {Lambda a. lambda {x}. x}"
  , Example "B1" "lambda f. <f 1, f true>"
  , Example "B1 (Fc translation 1)" "(lambda f. <f 1, f true>) : (forall a. a -> a) -> int * bool"
  , Example "B1 (Fc translation 2)" "lambda f : forall a. a -> a. <f 1, f true>"
  , Example "B1 (uncurried)" "lambda {f}. <f 1, f true>"
  , Example "B1 (Fc translation 1, uncurried)" "(lambda {f}. <f 1, f true>) : {forall a. {a} -> a} -> int * bool"
  , Example "B1 (Fc translation 2, uncurried)" "lambda {f : forall a. {a} -> a}. <f 1, f true>"
  , Example "B2" "lambda xs. poly (head xs)"
  , Example "B2 (Fc translation 1)" "(lambda xs. poly (head xs)) : [forall a. a -> a] -> int * bool"
  , Example "B2 (Fc translation 2)" "lambda xs : [forall a. a -> a]. poly (head xs)"
  , Example "B2 (uncurried)" "lambda {xs}. poly {head {xs}}"
  , Example "B2 (Fc translation 1, uncurried)" "(lambda {xs}. poly {head {xs}}) : {[forall a. {a} -> a]} -> int * bool"
  , Example "B2 (Fc translation 2, uncurried)" "lambda {xs : [forall a. {a} -> a]}. poly {head {xs}}"
  , Example "C1" "length ids"
  , Example "C1 (uncurried)" "length {ids}"
  , Example "C2" "tail ids"
  , Example "C2 (uncurried)" "tail {ids}"
  , Example "C3" "head ids"
  , Example "C3 (uncurried)" "head {ids}"
  , Example "C4" "single id"
  , Example "C4 (uncurried)" "single {id}"
  , Example "C5" "cons id ids"
  , Example "C5 (uncurried)" "cons {id, ids}"
  , Example "C6" "cons (lambda x. x) ids"
  , Example "C6 (Fc translation 1)" "cons (Lambda a. lambda x. x : a -> a) ids"
  , Example "C6 (Fc translation 2)" "cons (Lambda a. lambda x : a. x) ids"
  , Example "C6 (uncurried)" "cons {lambda {x}. x, ids}"
  , Example "C6 (Fc translation 1, uncurried)" "cons {(Lambda a. lambda {x}. x : {a} -> a), ids}"
  , Example "C6 (Fc translation 2, uncurried)" "cons {(Lambda a. lambda {x : a}. x), ids}"
  , Example "C7" "append (single inc) (single id)"
  , Example "C7 (Fc translation)" "append (single inc) (single (id @ int))"
  , Example "C7 (uncurried)" "append {single {inc}, single {id}}"
  , Example "C7 (Fc translation, uncurried)" "append {single {inc}, single {id @ int}}"
  , Example "C8" "append (single id) ids"
  , Example "C8 (uncurried)" "append {single {id}, ids}"
  , Example "C9" "map poly (single id)"
  , Example "C9 (uncurried)" "map {poly, single {id}}"
  , Example "C10" "map head (single ids)"
  , Example "C10 (Fc translation)" "map (head @ (forall a. a -> a)) (single ids)"
  , Example "C10 (uncurried)" "map {head, single {ids}}"
  , Example "C10 (Fc translation, uncurried)" "map {(head @ (forall a. {a} -> a)), single {ids}}"
  , Example "D1" "app poly id"
  , Example "D1 (uncurried)" "app {poly, id}"
  , Example "D2" "revapp id poly"
  , Example "D2 (uncurried)" "revapp {id, poly}"
  , Example "D3" "runST argST"
  , Example "D3 (uncurried)" "runST {argST}"
  , Example "D4" "app runST argST"
  , Example "D4 (Fc translation 1)" "app (lambda x. runST (Lambda a. x @ a) : (forall a. ST a int) -> int) argST"
  , Example "D4 (Fc translation 2)" "app (lambda x : forall a. ST a int. runST (Lambda a. x @ a)) argST"
  , Example "D4 (Fc translation 3)" "app (runST @ int) argST"
  , Example "D4 (uncurried)" "app {runST, argST}"
  , Example "D4 (Fc translation 1, uncurried)" "app {(lambda {x}. runST {Lambda a. x @ a} : {forall a. ST a int} -> int), argST}"
  , Example "D4 (Fc translation 2, uncurried)" "app {(lambda {x : forall a. ST a int}. runST {Lambda a. x @ a}), argST}"
  , Example "D4 (Fc translation 3, uncurried)" "app {runST @ int, argST}"
  , Example "D5" "revapp argST runST"
  , Example "D5 (Fc translation 1)" "revapp argST (runST @ int)"
  , Example "D5 (Fc translation 2)" "revapp argST (lambda x. runST (Lambda a. x @ a) : (forall a. ST a int) -> int)"
  , Example "D5 (uncurried)" "revapp {argST, runST}"
  , Example "D5 (Fc translation 1, uncurried)" "revapp {argST, (runST @ int)}"
  , Example "D5 (Fc translation 2, uncurried)" "revapp {argST, (lambda {x}. runST {Lambda a. x @ a} : {forall a. ST a int} -> int)}"
  , Example "E1" "k h lst"
  , Example "E1 (uncurried)" "k {h} {lst}"
  , Example "E2" "k (lambda x. h x) lst"
  , Example "E2 (Fc translation 1)" "k (Lambda a. lambda x. h x @ a : int -> a -> a) lst"
  , Example "E2 (Fc translation 2)" "k (Lambda a. lambda x : int. h x @ a) lst"
  , Example "E2 (uncurried)" "k {lambda {x}. h {x}} {lst}"
  , Example "E2 (Fc translation 1, uncurried)" "k {(Lambda a. lambda {x}. h {x} @ a : {int} -> {a} -> a)} {lst}"
  , Example "E2 (Fc translation 2, uncurried)" "k {(Lambda a. lambda {x : int}. h {x} @ a)} {lst}"
  , Example "E3" "r (lambda x. lambda y. y)"
  , Example "E3 (Fc translation 1)" "r (Lambda a. (lambda x. Lambda b. lambda y. y) : a -> forall b. b -> b)"
  , Example "E3 (Fc translation 2)" "r (Lambda a. lambda x : a. Lambda b. lambda y : b. y)"
  , Example "E3 (uncurried)" "r {lambda {x}. lambda {y}. y}"
  , Example "E3 (Fc translation 1, uncurried)" "r {(Lambda a. (lambda {x}. Lambda b. lambda {y}. y) : {a} -> forall b. {b} -> b)}"
  , Example "E3 (Fc translation 2, uncurried)" "r {(Lambda a. lambda {x : a}. Lambda b. lambda {y : b}. y)}"
  , Example "F5" "auto id"
  , Example "F5 (uncurried)" "auto {id}"
  , Example "F6" "cons (head ids) ids"
  , Example "F6 (uncurried)" "cons {head {ids}, ids}"
  , Example "F7" "head ids 3"
  , Example "F7 (uncurried)" "head {ids} {3}"
  , Example "F8" "choose (head ids)"
  , Example "Pair" "<lambda x. x, 1> : (int -> int) * int"
  , Example "Const" "(Lambda a. Lambda b. lambda x : a. lambda y : b. x) 1 true"
  , Example "Const (uncurried)" "(Lambda a. Lambda b. lambda {x : a}. lambda {y : b}. x) {1} {true}"
  , Example "Pair0" "(fst <lambda x. x, 2>) : int -> int"
  , Example "Pair1" "fst f"
  , Example "Pair2" "(fst f) 1"
  , Example "Pair3" "(fst <id, 1>) 1"
  ]  